In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

from sklearn import datasets

In [35]:
# importando dos dados

data_set = datasets.load_iris()
X = pd.DataFrame(data= data_set.data, columns=data_set.feature_names)
Y = pd.DataFrame(data= data_set.target)

display(X)
display(Y)
print(data_set.target_names)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

     0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

['setosa' 'versicolor' 'virginica']

In [41]:
# pré processamento

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = pd.DataFrame(data=scaler.fit_transform(X), columns= list(X.columns))
display(X)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [56]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
14           -0.052506          2.169988          -1.453901         -1.315444
98           -0.900681         -1.282963          -0.430828         -0.130755
75            0.916837         -0.131979           0.364896          0.264142
16           -0.537178          1.939791          -1.397064         -1.052180
131           2.492019          1.709595           1.501645          1.053935
56            0.553333          0.558611           0.535409          0.527406
141           1.280340          0.098217           0.762758          1.448832
44           -0.900681          1.709595          -1.056039         -1.052180
29           -1.385353          0.328414          -1.226552         -1.315444
120           1.280340          0.328414           1.103783          1.448832
94           -0.294842         -0.822570           0.251221          0.132510
5            -0.537178          1.939791          -1.169714         -1.052180
102           1.522676         -0.131979           1.217458          1.185567
51            0.674501          0.328414           0.421734          0.395774
78            0.189830         -0.362176           0.421734          0.395774
42           -1.748856          0.328414          -1.397064         -1.315444
92           -0.052506         -1.052767           0.137547          0.000878
66           -0.294842         -0.131979           0.421734          0.395774
31           -0.537178          0.788808          -1.283389         -1.052180
35           -1.021849          0.328414          -1.453901         -1.315444
90           -0.416010         -1.052767           0.364896          0.000878
84           -0.537178         -0.131979           0.421734          0.395774
77            1.038005         -0.131979           0.705921          0.659038
40           -1.021849          1.019004          -1.397064         -1.183812
125           1.643844          0.328414           1.274295          0.790671
99           -0.173674         -0.592373           0.194384          0.132510
33           -0.416010          2.630382          -1.340227         -1.315444
19           -0.900681          1.709595          -1.283389         -1.183812
73            0.310998         -0.592373           0.535409          0.000878
146           0.553333         -1.282963           0.705921          0.922303
91            0.310998         -0.131979           0.478571          0.264142
135           2.249683         -0.131979           1.331133          1.448832
69           -0.294842         -1.282963           0.080709         -0.130755
128           0.674501         -0.592373           1.046945          1.185567
114          -0.052506         -0.592373           0.762758          1.580464
48           -0.658345          1.479398          -1.283389         -1.315444
53           -0.416010         -1.743357           0.137547          0.132510
28           -0.779513          0.788808          -1.340227         -1.315444
54            0.795669         -0.592373           0.478571          0.395774
108           1.038005         -1.282963           1.160620          0.790671
112           1.159173         -0.131979           0.990108          1.185567
17           -0.900681          1.019004          -1.340227         -1.183812
119           0.189830         -1.973554           0.705921          0.395774
103           0.553333         -0.362176           1.046945          0.790671
58            0.916837         -0.362176           0.478571          0.132510
118           2.249683         -1.052767           1.785832          1.448832
18           -0.173674          1.709595          -1.169714         -1.183812
4            -1.021849          1.249201          -1.340227         -1.315444
45           -1.264185         -0.131979          -1.340227         -1.183812
59           -0.779513         -0.822570           0.080709          0.264142

In [83]:
# modelando

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier

X_train, X_test, y_train, y_test = train_test_split(X.values, Y.values.ravel(), random_state=1, 
                                                    test_size=0.8)

model = GradientBoostingClassifier()
model.fit(X.values,Y.values.ravel())
y_pred = model.predict(X_test)
model.score(X_test, y_test)

1.0

In [84]:
# Avaliação

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print("----- matriz da confusão ----- \n")
display(confusion_matrix(y_test, y_pred))
print("\n\n\n")
print("----- relatório de resultados ----- \n")
print(classification_report(y_test, y_pred, target_names=data_set.target_names))

# resultados muito bons, não necessário fazer a tunagem.

----- matriz da confusão -----

array([[40,  0,  0],
       [ 0, 37,  0],
       [ 0,  0, 43]], dtype=int64)

----- relatório de resultados -----

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        40
  versicolor       1.00      1.00      1.00        37
   virginica       1.00      1.00      1.00        43

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [ ]:
# salvando

import pickle

pickle.dump(model, open("modelos/iris_model.sav", "wb"))
pickle.dump(scaler, open("modelos/iris_scaler.sav", "wb"))